[project]
name = "jupyter-kernel-mcp"
version = "0.1.0"
description = "MCP server providing AI assistants with persistent Jupyter kernel execution"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = [
    "fastmcp",
    "httpx",
    "websockets",
]